name: Builder Workflow (Reusable)

on: [push, pull_request]

jobs:
  build:
    name: "Using Reusable"
    uses: thomas-bc/project-builder/.github/workflows/project-builder.yml
    with: 
      project_location: 'SampleDeployment'
