name: Builder Workflow (Reusable)

on: [push, pull_request]

jobs:
  build:
    name: ""
    uses: thomas-bc/project-builder/.github/workflows/project-builder.yml@main
    with: 
      build_location: SampleDeployment
