name: Builder Workflow (Reusable Workflow)

on: [push, pull_request]

jobs:
  build:
    name: ""
    uses: fprime-community/project-builder/.github/workflows/project-builder.yml@main
    with: 
      run_unit_tests: true
      build_location: SampleDeployment
